- Test different mime types: http://www.johnpanzer.com.kumbaya.io/JohnPanzerResume.pdf
- Test images: http://www.johnpanzer.com.kumbaya.io/me.jpg
- 404s: http://johnpanzer.com.kumbaya.io/ucscx-stl-fall00/
- HTTPS: https://techcrunch.com.kumbaya.io/2016/11/21/oracle-acquires-dns-provider-dyn-subject-of-a-massive-ddos-attack-in-october/
- 302s: http://music.gravitasrecordings.com.kumbaya.io/help/downloading?from=tralbum_downloading
- parameters: http://www.imdb.com.kumbaya.io/search/name?birth_place=Cincinnati,%20Ohio,%20USA&ref_=nm_ov_bth_place
- 
